### ISSUE TITLE
Getting "UNIQUE constraint failed: player.player_id" while running setup_airsenal_database

### ISSUE THREAD

**Issue by danarwix** [alan-turing-institute/AIrsenal#76] opened 2019-08-23 17:43 UTC
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: player.player_id
[SQL: INSERT INTO player (player_id, name) VALUES (?, ?)]
[parameters: ((1, 'Shkodran Mustafi'), (2, 'Héctor Bellerín'), (3, 'Sead Kolasinac'), (4, 'Ainsley Maitland-Niles'), (5, 'Sokratis Papastathopoulos'), (6, 'Nacho Monreal'), (7, 'Laurent Koscielny'), (8, 'Konstantinos Mavropanos')  ... displaying 10 of 529 total bound parameter sets ...  (487, 'Patrick Cutrone'), (528, 'Pedro Lomba Neto'))]
(Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by mazhar-debug** [comment] 2019-08-25 06:52
I'm having the same issue; running both Hyper-V and Virtualbox with latest Ubuntu.

**Comment by anguswilliams91** [comment] 2019-08-26 07:55
I can also reproduce this error.

**Comment by jack89roberts** [comment] 2019-08-26 09:54
I think I have found the problem and fixed this, though I'm not sure why we wouldn't have been getting errors before this week. I'd like to understand that before merging the fix to master in case I'm breaking something else, but you can use this branch in the meantime:

https://github.com/alan-turing-institute/AIrsenal/tree/fix/unique_playerid_violation

**Comment by HSherwani** [comment] 2019-08-27 10:47
still same issue persists.

**Comment by jack89roberts** [comment] 2019-08-29 15:57
Fix merged into master so closing this issue.

**Comment by danarwix** [comment] 2019-09-20 17:00
Thanks @jack89roberts 
From what I have found, in case the team was constructed after game week 1 the error occurred.

**Comment by chiefsan** [comment] 2020-03-12 10:36
I get the same output when running setup_airsenal_database

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: player.player_id                                                                                                                 [SQL: INSERT INTO player (player_id, name) VALUES (?, ?)]                                                                                                                                                          [parameters: ((1, 'Shkodran Mustafi'), (2, 'Héctor Bellerín'), (3, 'Sead Kolasinac'), (4, 'Ainsley Maitland-Niles'), (5, 'Sokratis Papastathopoulos'), (6, 'Nacho Monreal'), (7, 'Laurent Koscielny'), (8, 'Konstantinos Mavropanos')  ... displaying 10 of 628 total bound parameter sets ...  (609, 'Bruno André Cavaco Jordao'), (619, 'Daniel Castelo Podence'))]                                                                 (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by jack89roberts** [comment] 2020-03-12 11:52
@chiefsan Is it possible you already have a previous version of the database (or a partially completed one). You'll get that error if you run `setup_airsenal_database` when a database already exists (which is something we should fix).

Do you still get it if you do this?
```bash
> rm /tmp/data.db
> setup_airsenal_database
```

**Comment by chiefsan** [comment] 2020-03-13 05:24
Nope, I don't have a previous version of the database. 

Since the error was related to the unique constraint player.player_id, I modified the code to print the total number of player.player_ids and number of unique player ids. Both were reported as 628. I haven't been able to figure out where the problem is.

**Comment by jack89roberts** [comment] 2020-03-15 19:11
What OS are you running on (Linux/OS X/Windows)? Could you send me the last line it prints before the error (should be something like `Doing James Milner for 1819 season`), and upload a copy of your `/tmp/data,db` file? And was your team created in gameweek 1 or a later gameweek?

**Comment by chiefsan** [comment] 2020-03-20 12:02
I'm running on Windows. 
The last line printed before the error is `1920 adding Daniel Castelo Podence`

I don't have a database file yet. This is the first time I'm setting up the database.

**Comment by jack89roberts** [comment] 2020-03-20 17:27
Ah, we haven't managed to get it working properly on Windows yet unfortunately. Have you tried installing airsenal from the `fix/128-travis-windows` branch, by doing `git checkout fix/128-travis-windows` before `pip install .` in the installation instructions (there are more details in the repo readme)?

One of the issues is that `/tmp` is not a valid directory path on Windows. On that branch the database will be saved in whichever directory is returned by:
```bash
> python
>>> import tempfile
>>> tempfile.gettempdir()
```
So make sure there isn't a `data.db` file in there before running `setup_airsenal_database`.

This should let you create the database successfully, but we still have errors on Windows when running the predictions (#120 ). So I'm not sure uploading a `data.db` file would help you 😞.

**Comment by chiefsan** [comment] 2020-03-22 08:07
I installed airsenal from `fix/128-travis-windows` branch and it works now. I also installed Ubuntu(WSL) where there is no problem when running the predictions.  Thank you!

**Closed** 2020-03-22 13:55 UTC
Labels: bug
