### ISSUE TITLE
Initial DB setup failure

### ISSUE THREAD

**Issue by carlmacdiarmada** [alan-turing-institute/AIrsenal#246] opened 2020-09-15 11:36 UTC
Hi,

I have an error when running the initial db setup

```
Data not available for player 35 week 1
Traceback (most recent call last):
  File "c:\users\carl\.conda\envs\airsenalenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\carl\.conda\envs\airsenalenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Carl\.conda\envs\airsenalenv\Scripts\airsenal_setup_initial_db.exe\__main__.py", line 7, in <module>
  File "c:\users\carl\.conda\envs\airsenalenv\lib\site-packages\airsenal\scripts\fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "c:\users\carl\.conda\envs\airsenalenv\lib\site-packages\airsenal\framework\transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range
```

team : https://fantasy.premierleague.com/entry/2007170/event/1 

I have tried the fix outline [here](https://github.com/alan-turing-institute/AIrsenal/issues/244#issuecomment-692608772) but unfortunately no joy

**Comment by jack89roberts** [comment] 2020-09-15 11:54
Hi @carlmacdiarmada - thanks for letting us know. If you don't mind I'll close this issue and keep the discussion in #244.

**Closed by jack89roberts** 2020-09-15 11:54 UTC

**Comment by carlmacdiarmada** [comment] 2020-09-15 11:56
> Hi @carlmacdiarmada - thanks for letting us know. If you don't mind I'll close this issue and keep the discussion in #244.

no prob Jack, apologies, wasnt sure if it was the same issue or at a different stage, will track 244. Thanks

**Comment by jack89roberts** [comment] 2020-09-15 12:00
No probs, it looks to me like it's the same bug that's being encountered at lots of different stages. Probably something caused by some teams not having fixtures in gameweek 1, which isn't something we've had to deal with before!
