### ISSUE TITLE
GW2 optimization error

### ISSUE THREAD

**Issue by kreshnaa-raam** [alan-turing-institute/AIrsenal#404] opened 2021-08-16 10:12 UTC
[](url)AttributeError: Can't pickle local object 'run_optimization.<locals>.update_progress' - I am getting this attribute error when I try to run **airsenal_run_optimization --weeks_ahead 3.**

airsenal_run_prediction --weeks_ahead 3 - this runs successfully.
![Screenshot 2021-08-16 at 3 39 33 PM](https://user-images.githubusercontent.com/52041687/129547989-6fd2ca49-f515-4eba-bda2-963748d2bbef.png)

**Comment by nbarlowATI** [comment] 2021-08-16 12:13
Hi @kreshnaa-raam sorry to hear this isn't working.
Are you running on Windows, Linux, Mac ?   It looks like the problem is related to multiprocessing, which I think does behave slightly differently on different OSs.
Perhaps this could be worked around by running single-threaded:
```
airsenal_run_optimization --weeks_ahead 3 --num_thread 1
```
(could be worth a try at least...)

**Comment by kreshnaa-raam** [comment] 2021-08-16 12:28
@nbarlowATI thanks for the suggestion. I am using it on MAC. --num_thread also didn't help. I shall try it on windows and update if it works.

**Comment by jack89roberts** [comment] 2021-08-16 12:43
Would you be able to try on Python 3.7 if possible (e.g. using the conda environment described in the readme)? It looks like you're using Python 3.8? I don't think we've seen this specific issue before but we\ve had similar multiprocessing/pickle type issues before that, and on my Macbook they don't come up on 3.7.

**Comment by JPKFin** [comment] 2021-08-16 13:03
This problem has to do with the fact that defaults for multiprocessing changed in Python 3.8
Hence, OSX defaults to starting processes by spawn (instead of fork) on 3.8 and later.
A workaround/fix is to add the following
--
`multiprocessing.set_start_method("fork")`
--
before calling set_optimization function in fill_transfersuggestion_table.py

Did the above and got everything working (well, I have Python 3.9, but should work in 3.8 as well)

**Comment by jack89roberts** [comment] 2021-08-16 13:04
Nice, thanks! If you're able to make a pull request with that change in that would be very welcome!

**Comment by JPKFin** [comment] 2021-08-16 13:09
I haven't checked whether this change would have any adverse effects on 3.7 (don't have that environment that can also build scipy on my M1 MacBook) - suppose you guys could verify that this doesn't break anything ?

**Comment by jack89roberts** [comment] 2021-08-16 13:24
Yes we can take a look on 3.7 and check nothing breaks 🙂 (though I'd much rather have the default AIrsenal environment be 3.8/3.9 anyway, if everything works there)

**Comment by JPKFin** [comment] 2021-08-17 09:33
Made the pull request - forgot to tag @jack89roberts though.

**Comment by jack89roberts** [comment] 2021-08-17 09:41
That's great, thanks! I'll try to look at it this week, it will then get merged to our `develop`  branch before being merged to main in the next AIrsenal release.

**Closed** 2021-09-21 21:48 UTC
Labels: bug
