### ISSUE TITLE
Couldn't find FPL_LEAGUE_ID - some data may be unavailable

### ISSUE THREAD

**Issue by JoakimAE** [alan-turing-institute/AIrsenal#247] opened 2020-09-15 16:56 UTC
Thanks for the great work!

I experience the same issue as described in Initial setup issue #203
Note that I did follow the "new" description mentioned there, where the file name is: FPL_TEAM_ID and the content is only the numbers, nothing more.

Also note that I was able to run the prediction before the first round and get a recommended team (that performed quite well :) ).

However, now, when preparing for the second round, it doesn't seem to work and I was wondering if this could be the reason.
Anyway, I'm pasting the result here. Hope that is ok. 

Note: At the very bottom you can the the list of files in the folder, in indeed the FPL_TEAM_ID is there.

Thanks again,
Joakim

```
(airsenalenv) joakim@LAPTOP-4Q6CJBF4:/AIrsenal/airsenal/data$ airsenal_run_prediction --weeks_ahead 3
Couldn't find FPL_LEAGUE_ID - some data may be unavailable
Couldn't find FPL_TEAM_ID - some data may be unavailable
Couldn't find FPL_LOGIN - some data may be unavailable
Couldn't find FPL_PASSWORD - some data may be unavailable
Adding new team LEE with covariates
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_8c4b3dae224ed40cd55af0e4da27a5f1 NOW.
Generating player history dataframe - slow
Generating player history dataframe - slow
Generating player history dataframe - slow
Finished adding predictions to db for GK
Finished processing DONE
Process Process-8:
Traceback (most recent call last):
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: file is not a database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 65, in allocate_predictions
    pos, gw_range, team_model, player_model, season, tag, session
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 44, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 318, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 470, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 427, in process_player_data
    df = get_player_history_df(prefix, season=season, session=session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 69, in get_player_history_df
    position=position, season=season, dbsession=session, gameweek=gameweek
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py", line 400, in list_players
    fixtures = get_fixtures_for_gameweek(gameweek, season=season, dbsession=dbsession)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py", line 600, in get_fixtures_for_gameweek
    .filter_by(gameweek=gameweek)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: SELECT fixture.fixture_id AS fixture_fixture_id, fixture.date AS fixture_date, fixture.gameweek AS fixture_gameweek, fixture.home_team AS fixture_home_team, fixture.away_team AS fixture_away_team, fixture.season AS fixture_season, fixture.tag AS fixture_tag, fixture.player_id AS fixture_player_id
FROM fixture
WHERE fixture.season = ? AND fixture.gameweek = ?]
[parameters: ('2021', 2)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
Process Process-6:
Traceback (most recent call last):
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 65, in allocate_predictions
    pos, gw_range, team_model, player_model, season, tag, session
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 44, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 318, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 470, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 435, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 409, in get_empirical_bayes_estimates
    a0 = neff * (goals / team) * (total_minutes / minutes)
ZeroDivisionError: division by zero
Process Process-7:
Traceback (most recent call last):
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 65, in allocate_predictions
    pos, gw_range, team_model, player_model, season, tag, session
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 44, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 318, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 470, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 435, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/home/joakim/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/prediction_utils.py", line 409, in get_empirical_bayes_estimates
    a0 = neff * (goals / team) * (total_minutes / minutes)
ZeroDivisionError: division by zero
==================================================
PREDICTED TOP 5 PLAYERS FOR GAMEWEEK(S) [2, 3, 4]:
==================================================
GK:
-------------------------
DEF:
-------------------------
MID:
-------------------------
FWD:
-------------------------
(airsenalenv) joakim@LAPTOP-4Q6CJBF4:/AIrsenal/airsenal/data$ ls
FD_API_KEY                  fixtures.csv              player_summary_1617.json  results_1819_with_gw.csv
FPL_1718.json               gameweeks.txt             player_summary_1718.json  results_1920.csv
FPL_1819.json               player_details_1516.json  player_summary_1819.json  results_1920_with_gw.csv
FPL_1920.json               player_details_1617.json  player_summary_1920.json  teams_1516.csv
FPL_LEAGUE_ID               player_details_1718.json  results_1415.csv          teams_1617.csv
FPL_LOGIN                   player_details_1819.json  results_1516.csv          teams_1718.csv
FPL_PASSWORD                player_details_1920.json  results_1516_with_gw.csv  teams_1819.csv
FPL_TEAM_ID                 player_history_DEF.csv    results_1617.csv          teams_1920.csv
fifa_team_ratings_1819.csv  player_history_FWD.csv    results_1617_with_gw.csv  teams_2021.csv
fifa_team_ratings_1920.csv  player_history_GK.csv     results_1718.csv          transactions.csv
fifa_team_ratings_2021.csv  player_history_MID.csv    results_1718_with_gw.csv
fixture_data_1920.json      player_summary_1516.json  results_1819.csv
(airsenalenv) joakim@LAPTOP-4Q6CJBF4:/AIrsenal/airsenal/data$
```

**Comment by jack89roberts** [comment] 2020-09-15 20:48
Hi @JoakimAE , I think there might be a few different things going on here.

The problem about not finding the FPL_TEAM_ID looks like #77 , where the suspicion was that this was caused by installing the package before the files had been created. Could you try force reinstalling AIrsenal and see if that fixes it (i.e. removes the "could not find" messages)? With your environment activated and from the parent "AIrsenal" repo directory run:
```shell
pip install --upgrade --force-reinstall .
```

Second, the message `sqlite3.DatabaseError: file is not a database` suggests the database setup either hasn't been run or that it failed (maybe because of the team ID error above). Before running the prediction make sure to run `airsenal_setup_initial_db` and `airsenal_update_db` first.

Third, it's also possible you're encountering #244 , which I'm about to look into. That should only be a problem if you had any Man City, Man Utd, Aston Villa or Burnley players in your squad for gameweek 1 (i.e. any player without a fixture scheduled for gameweek 1).

I hope some combination of all that helps!

**Comment by Tdarnell** [comment] 2020-09-16 11:19
I experienced these same sqlite issues on WSL Ubuntu - they were fixed by switching from conda to python as explained in #81 

The league not found is to do with running the pip install before creating the FPL_LEAGUE_ID, as described above

**Comment by JoakimAE** [comment] 2020-09-16 19:35
@jack89roberts : Thanks for the thorough feedback.

Step 1 and 2 fixed the issue with not finding the FPL_TEAM_ID.

However, as you pointed out: For those of us who had players from the mentioned teams in our squad, issue #244 could also kick in. So it did for me.
But again, your workaround mentioned there, did the trick. 

rm /tmp/data.db
git checkout develop
git pull
pip install --upgrade --force-reinstall . 

I have now run the prediction successfully and it is currently working on the best strategy. It is not at 22% and based on the time it has taken to get there, the full job will take approximately 4-5 hours. Is that to be expected?

One more thing; Ceteris paribus (all other things the same); won't the AI suggest the same team for all of us and then next, suggest the same swap of platyers? I mean, we are all running the exact same code, so the outcome should be the same?

Again, thanks for the amazing job you guys do! 

Best regards
Joakim

**Comment by jack89roberts** [comment] 2020-09-16 21:17
The optimization is quite slow at the moment, that's another thing on the list of things to improve (there's already some work in progress). It will depend on your machine but on my laptop it takes about half an hour if running on the 12 cores I have available. The default is for it to run on 4 threads, so that would take more like 1h 30mins for me.

You can check how many threads you could run it on from a python shell like this:
```
python -c "import multiprocessing; print(multiprocessing.cpu_count())"
```
Then set the optimization to use that many threads like this:
```
airsenal_run_optimization --num_thread NUM_THREADS
```
(replace `NUM_THREADS` with the number you got from the command above)

For your other comments:
- Given the same starting squad and the same optimization parameters it should suggest the same transfer strategy, yes. However, generating the initial full squad has a random component to it, so `airsenal_make_team` will give slightly different results each time. There are also other options for the transfer optimization, e.g. how many weeks to optimize for, whether you want to play a chip etc. These are not very well documented at the moment but you can get some info from `airsenal_run_optimization --help`.

- Players flagged as orange or red on the FPL website should be given a predicted points of zero by AIrsenal, so are unlikely to be selected (though it's possible, e.g. for substitutes, or if the squad generation didn't successfully find a good solution). Players flagged yellow are currently assumed to play as normal. Definitely could be improved, but if you have orange/red players it's likely the optimization will recommend transferring them out.

**Comment by georgewhewell** [comment] 2020-09-18 15:51
i also have 'slow prediction' problem so i profiled this part of code and made some changes to improve performance, now takes 3mins for 3-week prediction on my machine (8 thread). if anyone interested i can tidy up and make PR. code is here https://github.com/georgewhewell/AIrsenal/tree/faster-suggestions

**Comment by jack89roberts** [comment] 2020-09-18 17:01
@georgewhewell That sounds great, please do open a PR and we'll take a look 🙂

**Comment by JoakimAE** [comment] 2020-09-18 20:12
Im running this on my wife's old computer and it only has 4 threads. Takes about 2h+, but that's to live with. Just gotta be on the alert during the christmas days. :)

**Comment by jack89roberts** [comment] 2020-09-18 20:46
Great, sounds like you've got it working so I'll close this issue, but feel free to make a new one if you have any other questions!

**Closed by jack89roberts** 2020-09-18 20:46 UTC
Labels: bug
