### ISSUE TITLE
`setup_airsenal_database` doesn't see environment variables as files

### ISSUE THREAD

**Issue by anguswilliams91** [alan-turing-institute/AIrsenal#77] opened 2019-08-26 07:43 UTC
In the readme, it says: "alternatively you can put the values into files in the airsenal/data/ directory, e.g. airsenal/data/FPL_TEAM_ID". I tried this, but when I subsequently run `setup_airsenal_database` I can see the following in the output:

```
Couldn't find FPL_LEAGUE_ID - some data may be unavailable
Couldn't find FPL_TEAM_ID - some data may be unavailable
Couldn't find FPL_LOGIN - some data may be unavailable
Couldn't find FPL_PASSWORD - some data may be unavailable
```

**Comment by jack89roberts** [comment] 2019-08-27 14:54
I think I've also seen this before and reverted to using environment variables, but as things stand I don't get any warning messages when using files in airsenal/data - so probably a tricky one to try to track down.

Is it possibly caused by creating the files after airsenal has been installed with `pip install .`? Could you try either creating the files before installation and/or installing the package in editable mode with `pip install -e .` and see if you still get the messages? I'll give that a go at some point too.

**Comment by nbarlowATI** [comment] 2019-10-09 07:54
I think Jack is right - I think the files are only picked up after having run ```pip install .```.   
I just setup from scratch on a new machine, and found this to be the case.  
Closing for now...

**Closed by nbarlowATI** 2019-10-09 07:54 UTC
Labels: bug
