### ISSUE TITLE
API Requests Connection Timeout Error (airsenal_setup_initial_db)

### ISSUE THREAD

**Issue by connorlhgs** [alan-turing-institute/AIrsenal#249] opened 2020-09-16 11:46 UTC
I've just tried running `airsenal_setup_initial_db`, and I get this error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: fifa_rating.team

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_db_init.py", line 21, in main
    make_fifa_ratings_table(session)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_fifa_ratings_table.py", line 41, in make_fifa_ratings_table
    session.commit()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
    cursor, statement, parameters, context
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: fifa_rating.team
[SQL: INSERT INTO fifa_rating (team, att, defn, mid, ovr) VALUES (?, ?, ?, ?, ?)]
[parameters: (('MCI', 87, 83, 86, 85), ('LIV', 87, 85, 83, 85), ('TOT', 85, 82, 82, 82), ('MUN', 83, 81, 81, 81), ('CHE', 80, 81, 84, 81), ('ARS', 84, 78, 82, 80), ('LEI', 80, 79, 79, 79), ('WHU', 82, 73, 78, 78)  ... displaying 10 of 33 total bound parameter sets ...  ('HUL', 68, 69, 68, 68), ('SUN', 67, 67, 67, 67))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

I'm not really sure where to go from here. Any help is appreciated.

**Comment by jack89roberts** [comment] 2020-09-16 12:25
I think you may have a previous database file - can you try deleting it and then running the setup?
```
rm /tmp/data.db
airsenal_setup_iniital_db
```

This is something we should catch and give a more meaningful error message.

**Comment by connorlhgs** [comment] 2020-09-16 12:39
That's fixed the original issue. However, now I get the following when I run the set-up:
```
Data not available for player 35 week 1
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range
```

**Comment by jack89roberts** [comment] 2020-09-16 13:28
Hi @connorlhgs - this is related to another problem we fixed yesterday, we have a fix on the development version of AIrsenal - see here for how to install the version with the fix: https://github.com/alan-turing-institute/AIrsenal/issues/244#issuecomment-693000842

**Comment by connorlhgs** [comment] 2020-09-16 15:16
@jack89roberts Unfortunately, I'm now getting the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/anaconda3/envs/airsenalenv/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 60] Operation timed out
```

I've uninstalled and reinstalled, including as suggested in #244, but each time I run the initial database set up I get the above error, or a similar one.

**Comment by jack89roberts** [comment] 2020-09-16 16:21
Looks like it's failing to get data from the FPL API, any chance you've been having internet issues today (or the device you're running on isn't connected)?

If not we can try using the underlying functions and see if they also fail. What do you get from doing the following in a python shell?
```
conda activate airsenalenv
python

from airsenal.framework.data_fetcher import FPLDataFetcher
fetcher = FPLDataFetcher()

fetcher.get_gameweek_data_for_player(1)

exit()
```

**Comment by connorlhgs** [comment] 2020-09-16 16:34
My connection has been good all day, as far as I know. 

Running that in a shell, I get the following:
`{1: [{'element': 1, 'fixture': 2, 'opponent_team': 8, 'total_points': 0, 'was_home': False, 'kickoff_time': '2020-09-12T11:30:00Z', 'team_h_score': 0, 'team_a_score': 3, 'round': 1, 'minutes': 0, 'goals_scored': 0, 'assists': 0, 'clean_sheets': 0, 'goals_conceded': 0, 'own_goals': 0, 'penalties_saved': 0, 'penalties_missed': 0, 'yellow_cards': 0, 'red_cards': 0, 'saves': 0, 'bonus': 0, 'bps': 0, 'influence': '0.0', 'creativity': '0.0', 'threat': '0.0', 'ict_index': '0.0', 'value': 70, 'transfers_balance': 0, 'selected': 76656, 'transfers_in': 0, 'transfers_out': 0}]}`

**Comment by jack89roberts** [comment] 2020-09-16 21:29
Yes, that's working as expected (they're Ozil's stats for gameweek 1 retrieved from the FPL API). But that makes this a tricky problem to diagnose, unfortunately (something is going wrong only when making many API calls, rather than just one, and this seems specific to your machine for some reason).

We could try to put in some extra checks for timeouts or reduce the rate of API calls, but I can't think of a quick fix.

**Comment by connorlhgs** [comment] 2020-09-16 21:32
No worries, I'll give it another go tomorrow.

Thanks for the help!

**Comment by nbarlowATI** [comment] 2020-09-17 14:58
I think I might have also seen this connection error, when trying to get player_details from the API, and putting a wait/retry in fixed it - I have this in a different branch, but will put into `develop` later today.

**Comment by nbarlowATI** [comment] 2020-09-18 08:29
Hi @connorlhgs - I just merged #254 into `develop`,  which will hopefully help with this - there's now a try/except around the call to the API, and if it gets a ConnectionError it will try up to 3 times with a 1 second wait between each.

**Comment by connorlhgs** [comment] 2020-09-18 09:44
Hello @nbarlowATI - it seems to be working, I'm not getting any more connection errors. However, when returning the scores for gameweek 1 it stops at player 35. There is no error message, just simply:

`Data not available for player 35 week 1`

I've cleared the database and forced the reinstall, as per #244, but it always stops at player 35.

**Comment by nbarlowATI** [comment] 2020-09-18 10:06
Hmm... so player 35 is Orjan Nyland (AVL keeper).  (you can see this via 
```
python
>>> from airsenal.framework.utils import get_player
>>> p = get_player(35)
>>> p.name
```
) who didn't have a match in week 1, so i can see why its printing that message, but it shouldn't be stopping there...   
Is this still in the `airsenal_setup_initial_db` stage?

**Comment by connorlhgs** [comment] 2020-09-18 10:10
Yes, this is still the `airsenal_setup_initial_db` stage. I've re-run all the steps a few times, but it never gets past Nyland.

**Comment by jack89roberts** [comment] 2020-09-18 11:49
I'm getting this but for Brandon Williams instead. What are the few lines before the "Data not available for player 35 week 1" message? I think it might be that the setup has worked up until getting your squad (the last step), which means it might be a bug with the fix I put in a couple of days ago.

**Comment by jack89roberts** [comment] 2020-09-18 12:36
In fact, I think everything has worked ok, it's just quite a confusing message. Can you run the rest of the steps normally @connorlhgs (`airsenal_update_db`, `airsenal_run_prediction`, `airsenal_run_optimization`)?

I've just added another print statement to make it clearer what's happening - basically it fails to get the price from gameweek 1 data (because those players don't have gameweek 1 data), but #244 means it now uses their current data to determine their starting prices.

**Comment by nbarlowATI** [comment] 2020-09-18 13:00
It's actually not clear to me:
* Why we don't seem to get this message for all players that didn't have a gw last week.
* Why it doesn't crash when we get this message - `data_fetcher.get_gameweek_data_for_player` is returning an empty list in this case, while `fill_playerscore_table.fill_playerscores_from_api` is expecting a dict (and calling `.items()` on it)...

I did just see the message (for a different player) when running `airsenal_setup_initial_db` but failed to reproduce it when running `fill_playerscores_from_api` directly...   

Will investigate further...

**Comment by nbarlowATI** [comment] 2020-09-18 13:24
OK, I'm still a bit confused about this list/dict thing, but I think @jack89roberts is right that the table is still being filled correctly - I just ran `airsenal_setup_initial_db` again, and the last message was a "Data not available for player 12 week 1" (Emiliano Martinez, who we could imagine is even more of an edge case as he was still an ARS player for gw1!).
But I checked the number of rows in the PlayerScore table, and the number (424) agrees with what I got in the previous test where I didn't see that message:
```
python
>>> from airsenal.framework.utils import *
>>> ps2021 = session.query(PlayerScore).filter(PlayerScore.fixture.has(Fixture.season=="2021")).all()
>>> len(pss2021)
424
```

So I think everything is working OK.

**Comment by connorlhgs** [comment] 2020-09-18 14:50
Yeah, I've just run everything and it all seems to be working fine!

**Closed** 2020-09-24 14:37 UTC
Labels: bug
